### ISSUE TITLE
Does not modify customData to actually link the accounts.

### ISSUE THREAD

**Issue by gchatter** [stormpath/stormpath-express-social-unification-example#1]
While this does create two accounts, it doesn't link or unify them because it doesn't modify the customData to point to the href of the social account in the main directory.  Is this intended in this example?

**Comment by rdegges** [comment]
This is the intended example -- instead of a direct link (which would pollute the user's custom data), this middleware will instead dynamically find the linked account by email address, and swap the sessions on demand.

Because this process happens only once (when the account first logs in), it is very inexpensive / fast to run =)
